name: birdman
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - python=3.8
  - cmdstanpy
  - python-language-server
  - xarray
  - patsy
  - arviz
  - biom-format
  - seaborn
