#!/bin/bash

set -e

pip install birdman==0.0.1
python -c "import cmdstanpy; cmdstanpy.install_cmdstan(version='2.25.0')"
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace notebooks/*.ipynb
