#!/bin/bash

set -e

pip install git+https://github.com/gibsramen/BIRDMAn.git
python -c "import cmdstanpy; cmdstanpy.install_cmdstan(version='2.25.0')"
jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace notebooks/*.ipynb
